import argparse
import json
import re
import signal
import traceback
from pathlib import Path

import training as _training
import telemetry as _telemetry
from training import *

def parser():
    root = argparse.ArgumentParser()
    commands = root.add_subparsers(dest="command", required=True)
    run = commands.add_parser("train")
    run._negative_number_matcher = re.compile(r"^-\d*\.?\d+(?:[eE][+-]?\d+)?$")
    run.add_argument("--output", default="target/v74")
    run.add_argument("--checkpoint")
    run.add_argument("--width", type=int)
    run.add_argument("--layers", type=int)
    run.add_argument("--heads", type=int)
    run.add_argument("--feedforward", type=int)
    for name in ("relic", "deck", "draw", "exhaust", "discard", "hand", "orb", "potion"):
        run.add_argument(f"--{name}-pooling", choices=COLLECTION_POOLING,
                         default=None)
    for name in ("enemy-effect", "friendly-effect"):
        run.add_argument(f"--{name}-pooling", choices=EFFECT_POOLING,
                         default=None)
    run.add_argument("--continuation-pooling", choices=CONTINUATION_POOLING,
                     default=None)
    run.add_argument("--phase-pooling", choices=("sum", "transformer"),
                     default=None)
    run.add_argument("--generation-pool-pooling", choices=("sum", "transformer"),
                     default=None)
    run.add_argument("--precision", choices=PRECISIONS, default="bf16")
    run.add_argument("--start-stage", type=int, default=6)
    run.add_argument("--hours", type=float, default=0)
    run.add_argument("--decisions", type=int, default=0)
    run.add_argument("--envs", type=int, default=512)
    run.add_argument("--samplers", type=int, default=2)
    run.add_argument("--torch-threads", type=int, default=2)
    run.add_argument("--sampler-threads", type=int, default=4)
    run.add_argument("--sampler-backend", choices=("process", "thread"), default="process")
    run.add_argument("--log-level", choices=("DEBUG", "INFO", "WARNING", "ERROR"), default="INFO")
    run.add_argument("--sampler-steps", type=int, default=4)
    run.add_argument("--sampler-timeout", type=float, default=120)
    run.add_argument("--sampler-restarts", type=int, default=3)
    run.add_argument("--mps-empty-cache-updates", type=int, default=4)
    run.add_argument("--segment-steps", type=int, default=0)
    run.add_argument("--publish-updates", type=int, default=8)
    run.add_argument("--report-decisions", type=int, default=32_768)
    run.add_argument("--save-decisions", type=int, default=262_144)
    run.add_argument("--max-policy-lag", type=int, default=20)
    run.add_argument("--max-log-ratio", type=float, default=.5)
    run.add_argument("--policy-temperature", type=float, default=.8)
    run.add_argument("--mcts-fraction", type=float, default=0)
    run.add_argument("--mcts-simulations", type=int, default=0)
    run.add_argument("--mcts-boss-simulations", type=int, default=0)
    run.add_argument("--mcts-turns", type=int, default=1)
    run.add_argument("--mcts-max-depth", type=int, default=64)
    run.add_argument("--mcts-batch-size", type=int, default=256)
    run.add_argument("--mcts-min-visits", type=int, default=16)
    run.add_argument("--mcts-max-targets", type=int, default=64)
    run.add_argument("--mcts-prior-temperature", type=float, default=1)
    run.add_argument("--mcts-q-temperature", type=float, default=.002)
    run.add_argument("--mcts-exploration", type=float, default=1.5)
    run.add_argument("--mcts-heuristic", action="store_true")
    run.add_argument("--mcts-timeout", type=float, default=0)
    run.add_argument("--expert-weight", type=float, default=.002)
    run.add_argument("--expert-max-lag", type=int, default=4)
    run.add_argument("--expert-batch", type=int)
    run.add_argument("--expert-capacity", type=int, default=131_072)
    run.add_argument("--dataset-capacity", type=int, default=131_072)
    run.add_argument("--batch", type=int, default=4096)
    run.add_argument("--learning-rate", type=float, default=3e-4)
    run.add_argument("--learning-rate-warmup-steps", type=int, default=200)
    run.add_argument("--head-learning-rate-multiplier", type=float, default=1)
    run.add_argument("--critic-learning-rate-multiplier", type=float, default=1)
    run.add_argument("--critic-only", action="store_true")
    run.add_argument("--freeze-backbone", action="store_true")
    run.add_argument("--gae-gamma", type=float, default=1.0)
    run.add_argument("--gae-lambda", type=float, default=1.0)
    for term in POTENTIAL_TERMS:
        run.add_argument(f"--potential-{term.replace('_', '-')}-weight", type=float, default=0.)
    run.add_argument("--critic-balance-decay", type=float, default=.99)
    run.add_argument("--critic-consistency-weight", type=float, default=0)
    run.add_argument("--critic-consistency-batch", type=int, default=1024)
    run.add_argument("--search-consistency-weight", type=float, default=0)
    run.add_argument("--search-consistency-batch", type=int, default=256)
    run.add_argument("--blended-critic", action="store_true")
    run.add_argument("--critic-win-ema-decay", type=float, default=.9)
    run.add_argument("--critic-blend-power", type=float, default=.4)
    run.add_argument("--progress-decisions", type=int, default=5_000_000)
    run.add_argument("--progress-beta", type=float)
    run.add_argument("--clip", type=float, default=0.2)
    run.add_argument("--value-weight", type=float, default=0.5)
    run.add_argument("--winning-loss-weight", type=float, default=0.1)
    run.add_argument("--winning-capacity", type=int, default=WINNING_CAPACITY)
    run.add_argument("--priority-decay", type=float, default=3)
    run.add_argument("--character-balanced", action="store_true")
    run.add_argument("--entropy-start", type=float, default=0.01)
    run.add_argument("--entropy-end", type=float, default=0.001)
    run.add_argument("--entropy-weight", type=float, default=.1)
    run.add_argument("--target-kl", type=float, default=0.004)
    run.add_argument("--disable-post-kl-check", action="store_true")
    run.add_argument("--training-seed", type=int, default=1_900_000_000)
    run.add_argument("--development-seed", type=int, default=3_500_000_000)
    run.add_argument("--development-runs", type=int, default=32)
    run.add_argument("--promotion-seed", type=int, default=3_700_000_000)
    run.add_argument("--promotion-window", type=int, default=200)
    run.add_argument("--promotion-trigger-rate", type=float, default=.2)
    run.add_argument("--promotion-runs", type=int, default=256)
    run.add_argument("--promote-win-rate", type=float, default=0.2)
    run.add_argument("--evaluation-batch", type=int, default=32)
    run.add_argument("--evaluation-max-steps", type=int, default=2048)
    run.add_argument("--evaluation-max-combat-steps", type=int, default=512)
    run.add_argument("--max-steps", type=int, default=65_536)
    run.add_argument("--max-combat-steps", type=int, default=2_048)
    run.add_argument("--seed", type=int, default=1)
    run.add_argument("--promote-now", action="store_true")
    evaluate_parser = commands.add_parser("evaluate")
    evaluate_parser.add_argument("checkpoint")
    evaluate_parser.add_argument("--output")
    evaluate_parser.add_argument("--ascension", type=int, default=0)
    evaluate_parser.add_argument("--bonus", type=int, default=24)
    evaluate_parser.add_argument("--validation-seed", type=int, default=3_500_000_000)
    evaluate_parser.add_argument("--runs", type=int, default=128)
    evaluate_parser.add_argument("--evaluation-batch", type=int, default=32)
    evaluate_parser.add_argument("--max-steps", type=int, default=2048)
    evaluate_parser.add_argument("--max-combat-steps", type=int, default=512)
    evaluate_parser.add_argument("--precision", choices=PRECISIONS, default="fp32")
    search_evaluation = commands.add_parser("evaluate-search-policies")
    search_evaluation.add_argument("checkpoint")
    search_evaluation.add_argument("--output", default="target/search-policy-evaluation.json")
    search_evaluation.add_argument(
        "--modes", nargs="+", choices=(
            "policy", "sampled", "exact", "heuristic", "combat", "combat-heuristic",
        ),
        default=("policy", "sampled", "exact"),
    )
    search_evaluation.add_argument("--runs", type=int, default=16)
    search_evaluation.add_argument("--batch", type=int, default=16)
    search_evaluation.add_argument("--characters", type=int, nargs="+", default=(0, 1, 2, 3, 4))
    search_evaluation.add_argument("--max-steps", type=int, default=2048)
    search_evaluation.add_argument("--max-combat-steps", type=int, default=512)
    search_evaluation.add_argument("--policy-temperature", type=float, default=.8)
    search_evaluation.add_argument("--simulations", type=int, default=128)
    search_evaluation.add_argument("--max-depth", type=int, default=64)
    search_evaluation.add_argument("--search-batch", type=int, default=256)
    search_evaluation.add_argument("--min-visits", type=int, default=16)
    search_evaluation.add_argument("--max-targets", type=int, default=64)
    search_evaluation.add_argument("--prior-temperature", type=float, default=3)
    search_evaluation.add_argument("--q-temperature", type=float, default=.002)
    search_evaluation.add_argument("--exploration", type=float, default=1.5)
    search_evaluation.add_argument("--exact-samples", type=int, default=16)
    search_evaluation.add_argument("--max-exact-states", type=int, default=100_000)
    search_evaluation.add_argument("--seed", type=int, default=4_620_000_000)
    final = commands.add_parser("finalize")
    final.add_argument("checkpoint")
    final.add_argument("--output", default="target/value/value.bin")
    final.add_argument("--fit-runs", type=int, default=256)
    final.add_argument("--calibration-runs", type=int, default=256)
    final.add_argument("--test-runs", type=int, default=1000)
    final.add_argument("--states-per-run", type=int, default=16)
    final.add_argument("--hours", type=float, default=12)
    final.add_argument("--batch", type=int, default=32)
    final.add_argument("--head-batch", type=int, default=1024)
    final.add_argument("--epochs", type=int, default=8)
    final.add_argument("--learning-rate", type=float, default=3e-4)
    final.add_argument("--fit-seed", type=int, default=4_100_000_000)
    final.add_argument("--calibration-seed", type=int, default=4_200_000_000)
    final.add_argument("--test-seed", type=int, default=4_300_000_000)
    final.add_argument("--max-steps", type=int, default=4096)
    final.add_argument("--max-combat-steps", type=int, default=512)
    final.add_argument("--precision", choices=PRECISIONS)
    final.add_argument("--seed", type=int, default=29)
    dashboard_parser = commands.add_parser("dashboard")
    dashboard_parser.add_argument("target", nargs="?", default="target")
    dashboard_parser.add_argument("--host", default="127.0.0.1")
    dashboard_parser.add_argument("--port", type=int, default=8000)
    search = commands.add_parser("search-diagnostics")
    search.add_argument("checkpoint")
    search.add_argument("--output", default="target/search-diagnostics-v68")
    search.add_argument("--roots", type=int, default=6)
    search.add_argument("--envs", type=int, default=64)
    search.add_argument("--max-steps", type=int, default=2048)
    search.add_argument("--sample-stride", type=int, default=64)
    search.add_argument("--simulations", type=int, default=128)
    search.add_argument("--max-depth", type=int, default=64)
    search.add_argument("--batch-size", type=int, default=256)
    search.add_argument("--prior-temperature", type=float, default=1)
    search.add_argument("--exploration", type=float, default=1.5)
    search.add_argument("--policy-temperature", type=float, default=.8)
    search.add_argument("--exact-samples", type=int, default=16)
    search.add_argument("--max-exact-states", type=int, default=100_000)
    search.add_argument("--max-pairs", type=int, default=200_000)
    search.add_argument("--progress-value", action="store_true")
    search.add_argument("--q-temperature", type=float, default=.002)
    search.add_argument("--seed", type=int, default=3_200_000_000)
    compare = commands.add_parser("compare-search")
    compare.add_argument("input", nargs="+")
    compare.add_argument("--output", default="target/search-diagnostics-comparison.html")
    critic = commands.add_parser("critic-diagnostics")
    critic.add_argument("checkpoint")
    critic.add_argument("--output", default="target/critic-diagnostics.json")
    critic.add_argument("--runs", type=int, default=64)
    critic.add_argument("--batch", type=int, default=32)
    critic.add_argument("--max-steps", type=int, default=2048)
    critic.add_argument("--max-combat-steps", type=int, default=512)
    critic.add_argument("--policy-temperature", type=float, default=.8)
    critic.add_argument("--precision", choices=PRECISIONS, default="fp32")
    critic.add_argument("--seed", type=int, default=3_600_000_000)
    commands.add_parser("probe")
    return root
if __name__ == "__main__":
    args = parser().parse_args()
    if args.command == "train":
        def terminate(number, _):
            signal.signal(signal.SIGINT, signal.SIG_IGN)
            signal.signal(signal.SIGTERM, signal.SIG_IGN)
            raise SystemExit(128 + number)
        signal.signal(signal.SIGINT, terminate)
        signal.signal(signal.SIGTERM, terminate)
        try:
            train(args)
        except BaseException as error:
            if _telemetry._LOG_ACTIVE:
                emit_event({
                    "event": "session_error", "error": repr(error),
                    "traceback": traceback.format_exc(),
                }, "ERROR")
            shutdown_logging()
            raise
    elif args.command == "finalize":
        finalize(args)
    elif args.command == "evaluate":
        target = device(); model, _ = load(args.checkpoint, target)
        report = evaluate(model, args, target)
        if args.output:
            immutable_json(Path(args.output), report)
        print(json.dumps(report, indent=2))
    elif args.command == "evaluate-search-policies":
        evaluate_search_policies(args)
    elif args.command == "dashboard":
        serve_dashboard(Path(args.target), args.host, args.port)
    elif args.command == "search-diagnostics":
        diagnose_search(args)
    elif args.command == "compare-search":
        compare_search(args)
    elif args.command == "critic-diagnostics":
        critic_diagnostics(args)
    else:
        probe()
